[package]
name = "threads-dummy-bench-rs"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 3

[[bin]]
name = "threads-dummy-bench"
path = "src/bin.rs"

[dependencies]
num-format = "0.4.3"
memory-stats = "1.0.0"
